# --------------------------------------------------------------------------
# THIS FILE IS AUTOGENERATED - DO NOT EDIT MANUALLY
#
# Source: Containerfile.j2
# --------------------------------------------------------------------------

# AdGuardHome Sync - Configuration Sync Tool
# Multi-stage build

ARG BASE_VERSION=15
FROM ghcr.io/daemonless/base:${BASE_VERSION} AS builder

# Install build dependencies
RUN pkg update && pkg install -y go125 git ca_root_nss

ARG UPSTREAM_URL="https://api.github.com/repos/bakito/adguardhome-sync/releases/latest"

# Build from source
RUN mkdir -p /app && \
    VERSION=$(fetch -qo - "${UPSTREAM_URL}" | jq -r '.tag_name') && \
    echo "Building AdGuardHome Sync ${VERSION}" && \
    git clone --depth 1 --branch "${VERSION}" https://github.com/bakito/adguardhome-sync.git /tmp/src && \
    cd /tmp/src && \
    CGO_ENABLED=0 /usr/local/bin/go125 build -ldflags="-s -w -X github.com/bakito/adguardhome-sync/version.Version=${VERSION}" -o /usr/local/bin/adguardhome-sync . && \
    echo "${VERSION}" > /app/version

# Production image
FROM ghcr.io/daemonless/base:${BASE_VERSION}

ARG FREEBSD_ARCH=amd64
ARG PACKAGES="ca_root_nss"
ARG UPSTREAM_URL="https://api.github.com/repos/bakito/adguardhome-sync/releases/latest"
ARG UPSTREAM_JQ=".tag_name"
ARG HEALTHCHECK_ENDPOINT="http://localhost:8080"

ENV HEALTHCHECK_URL="${HEALTHCHECK_ENDPOINT}"

# --- Metadata (Injected by Generator) ---
LABEL org.opencontainers.image.title="AdGuardHome Sync" \
      org.opencontainers.image.description="Sync AdGuardHome configuration to replica instances." \
      org.opencontainers.image.source="https://github.com/daemonless/adguardhome-sync" \
      org.opencontainers.image.url="https://github.com/bakito/adguardhome-sync" \
      org.opencontainers.image.documentation="https://github.com/bakito/adguardhome-sync" \
      org.opencontainers.image.licenses="Apache-2.0" \
      org.opencontainers.image.vendor="daemonless" \
      org.opencontainers.image.authors="daemonless" \
      io.daemonless.category="Network" \
      io.daemonless.port="8080" \
      io.daemonless.volumes="/config" \
      io.daemonless.arch="${FREEBSD_ARCH}" \
      io.daemonless.upstream-url="${UPSTREAM_URL}" \
      io.daemonless.upstream-jq="${UPSTREAM_JQ}" \
      io.daemonless.healthcheck-url="${HEALTHCHECK_ENDPOINT}" \
      io.daemonless.packages="${PACKAGES}"

# Install runtime dependencies
RUN pkg update && \
    pkg install -y ${PACKAGES} && \
    pkg clean -ay && \
    rm -rf /var/cache/pkg/* /var/db/pkg/repos/*

# Copy binary
COPY --from=builder /usr/local/bin/adguardhome-sync /usr/local/bin/adguardhome-sync
COPY --from=builder /app/version /app/version

RUN chmod 755 /usr/local/bin/adguardhome-sync

# Create config directory
RUN mkdir -p /config && \
    chown -R bsd:bsd /config

# Copy service definition
COPY root/ /

# Make scripts executable
RUN chmod +x /etc/services.d/*/run /etc/cont-init.d/* 2>/dev/null || true

# --- Expose (Injected by Generator) ---
EXPOSE 8080

# --- Volumes (Injected by Generator) ---
VOLUME /config